// ============================================================
// As Above, So Below. As Within, So Without.
// The Future Dictates the Past and the Past is Always Present.
// ============================================================

// lib/services/coach_tflite_intent_service.dart
//
// Optional on-device intent classifier for the scripted coach.
//  * Model asset is generated by tools/train_coach_intent.py (INT8 weights,
//    float I/O) and ships in assets/models/. When it is absent — or the
//    device is low-RAM — every method degrades gracefully to keywords.
//  * Crisis ALWAYS resolves via keyword before this model runs.

import 'dart:async';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:tflite_flutter/tflite_flutter.dart';

import 'recovery_coach_service.dart';

class CoachTfliteIntentService {
  static const String modelAsset = 'assets/models/coach_intent.tflite';
  static const String vocabAsset = 'assets/models/coach_intent_vocab.txt';
  static const int sentenceLen = 64;

  /// The tiny corpus keeps probabilities soft; ranking quality is what
  /// matters. Keep in spirit with the trainer's validation spread.
  static const double minConfidence = 0.14;

  /// Set true to skip the model entirely (low-RAM devices / settings toggle).
  static bool forceKeywordOnly = false;
  static int minFreeRamMb = 1024;
  static bool _available = false;
  static bool _loadAttempted = false;

  /// Order must match LABELS in tools/train_coach_intent.py.
  static const List<CoachIntent> labelOrder = [
    CoachIntent.crisis,
    CoachIntent.urge,
    CoachIntent.checkIn,
    CoachIntent.walk,
    CoachIntent.gratitude,
    CoachIntent.appHelpPet,
    CoachIntent.appHelpSos,
    CoachIntent.appHelpDresser,
    CoachIntent.greeting,
    CoachIntent.unknown,
  ];

  // Vocab specials — must match build_vocab() in the trainer.
  static const int padId = 0;
  static const int unkId = 1;
  static const int startId = 2;

  static Interpreter? _interpreter;
  static Map<String, int> _vocab = const {};

  static bool get isAvailable => _available;

  static Future<void> loadModel() async {
    if (_loadAttempted) return;
    _loadAttempted = true;
    if (forceKeywordOnly) return;
    try {
      // Tokenizer table; missing vocab file means the model cannot be used.
      final vocabRaw = await rootBundle.loadString(vocabAsset);
      final map = <String, int>{};
      for (final line in vocabRaw.split('\n')) {
        final trimmed = line.trim();
        if (trimmed.isEmpty) continue;
        final parts = trimmed.split(' ');
        if (parts.length != 2) continue;
        final idx = int.tryParse(parts[1]);
        if (idx == null) continue;
        map[parts[0]] = idx;
      }
      if (!map.containsKey('<START>') || map.length < 8) return;

      final options = InterpreterOptions()..threads = 1;
      _interpreter =
          await Interpreter.fromAsset(modelAsset, options: options);
      _vocab = Map.unmodifiable(map);
      _available = true;
      debugPrint(
          'CoachTfliteIntentService: model loaded (${_vocab.length} tokens)');
    } catch (e) {
      debugPrint('CoachTfliteIntentService load failed (keyword mode): $e');
      _interpreter?.close();
      _interpreter = null;
      _available = false;
    }
  }

  /// Mirrors encode() in tools/train_coach_intent.py exactly.
  @visibleForTesting
  static List<int> encode(String rawText, Map<String, int> vocab) {
    final ids = <int>[vocab['<START>'] ?? startId];
    for (final rawWord in rawText.toLowerCase().replaceAll("'", ' ').split(' ')) {
      final tok =
          rawWord.replaceAll(RegExp(r'[^a-z0-9]'), '');
      if (tok.isEmpty) continue;
      ids.add(vocab[tok] ?? unkId);
      if (ids.length >= sentenceLen) break;
    }
    while (ids.length < sentenceLen) {
      ids.add(padId);
    }
    return ids.sublist(0, sentenceLen);
  }

  static Future<CoachIntent?> classifyWithModel(String rawText) async {
    await loadModel();
    if (!_available || _interpreter == null) return null;
    try {
      final ids = encode(rawText, _vocab);

      // Graph takes float token IDs and casts internally; INT8 weights
      // produce float probabilities.
      final input = [
        Float32List.fromList(ids.map((e) => e.toDouble()).toList()),
      ];
      final output = [
        List<double>.filled(labelOrder.length, 0.0),
      ];

      _interpreter!.run(input, output);

      final probs = _softmax(output[0]);
      var bestProb = 0.0;
      var bestIdx = -1;
      for (var i = 0; i < probs.length; i++) {
        if (probs[i] > bestProb) {
          bestProb = probs[i];
          bestIdx = i;
        }
      }
      if (bestIdx < 0 || bestIdx >= labelOrder.length) return null;
      if (bestProb < minConfidence) return CoachIntent.unknown;
      return labelOrder[bestIdx];
    } catch (e) {
      debugPrint('CoachTfliteIntentService infer failed: $e');
      return null;
    }
  }

  static List<double> _softmax(List<double> logits) {
    final maxV = logits.reduce(max);
    final exps = logits.map((v) => exp(v - maxV)).toList();
    final sum = exps.fold<double>(0.0, (a, b) => a + b);
    if (sum == 0) {
      return List.filled(logits.length, 1.0 / logits.length);
    }
    return exps.map((e) => e / sum).toList();
  }

  /// Convenience pipeline: crisis keywords win, then model, else null to
  /// signal "fall back to scripted keywords".
  static Future<CoachIntent?> classify(String rawText) async {
    if (RecoveryCoachService.classify(rawText) == CoachIntent.crisis) {
      return CoachIntent.crisis;
    }
    if (forceKeywordOnly) return null;
    return classifyWithModel(rawText);
  }

  static void close() {
    _interpreter?.close();
    _interpreter = null;
    _available = false;
    _loadAttempted = false;
  }
}
