# ============================================================
# As Above, So Below. As Within, So Without.
# The Future Dictates the Past and the Past is Always Present.
# ============================================================
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED
org.gradle.java.home=C\:\\\\Users\\\\612co\\\\.jdks\\\\jbr-21.0.11
android.useAndroidX=true
android.overridePathCheck=true
org.gradle.daemon=false
# Disable configuration cache to avoid lock issues during troubleshooting
org.gradle.configuration-cache=false