# ============================================================
# As Above, So Below. As Within, So Without.
# The Future Dictates the Past and the Past is Always Present.
# ============================================================

# tools/generate_code_package.py
#
# Regenerates blueprints/recovery_all_code.md from the live working tree so
# the single-file transfer package can never drift from the real codebase.
#
# Usage:  python tools/generate_code_package.py   (run from repo root)

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_REL = os.path.join("blueprints", "recovery_all_code.md")

# (relative path, fence language tag)
TARGETS: list[tuple[str, str]] = []

# Top-level config first.
for rel, tag in [
    ("pubspec.yaml", "yaml"),
    ("analysis_options.yaml", "yaml"),
    ("android/app/build.gradle.kts", "kotlin"),
    ("android/app/src/main/AndroidManifest.xml", "xml"),
]:
    TARGETS.append((rel, tag))

# All hand-written Dart sources (generated Drift code is rebuilt via build_runner).
for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, "lib")):
    dirnames.sort()
    for name in sorted(filenames):
        if not name.endswith(".dart"):
            continue
        if name.endswith(".g.dart"):
            continue
        full = os.path.join(dirpath, name)
        rel = os.path.relpath(full, ROOT).replace("\\", "/")
        TARGETS.append((rel, "dart"))

# Blueprint documentation.
bp_dir = os.path.join(ROOT, "blueprints")
for name in sorted(os.listdir(bp_dir)):
    if name.endswith(".md") and name != "recovery_all_code.md":
        TARGETS.append((f"blueprints/{name}", "markdown"))

# Sprint plan + project notes.
for rel, tag in [("SPRINT_PLAN.md", "markdown"), ("CLAUDE.md", "markdown")]:
    if os.path.exists(os.path.join(ROOT, rel)):
        TARGETS.append((rel, tag))

LANG_TO_TAG = {"dart": "dart", "yaml": "yaml", "kotlin": "kotlin",
               "xml": "xml", "markdown": "markdown"}

HEADER = """# Recovery for All - Unified Source Code Package

> Generated by `tools/generate_code_package.py` from the live repository.
> Regenerate after any code change — never hand-edit this file.

## How to Extract This Code Locally
Save this entire document as `recovery_all_code.md`, place the following
Python script (`extract.py`) in the same directory, and run it:

```python
# extract.py
import os
import re

with open('recovery_all_code.md', 'r', encoding='utf-8') as f:
    content = f.read()

# Matches START_FILE markers with fences of 3+ backticks (nested-safe).
# Anchored to line starts so the marker text shown in this very script
# can never match itself.
pattern = re.compile(
    r'^## === START_FILE: (.+?) ===\n(`{3,})[^\n]*\n(.*?)\n\2',
    re.MULTILINE | re.DOTALL,
)
matches = pattern.findall(content)

for path, _fence, code in matches:
    path = path.strip()
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as out_f:
        out_f.write(code.strip() + '\\n')
    print(f"Extracted: {path}")

print("Extraction complete!")
```

## After Extracting — Build Steps
```bash
flutter pub get
dart run build_runner build --delete-conflicting-outputs   # regenerates *.g.dart
flutter analyze                                            # expect: No issues found
flutter build apk --debug                                  # expect: success
```

Notes for the collaborator:
- `lib/database/recovery_database.g.dart` is intentionally excluded; build_runner regenerates it from the schema (v6).
- The Meeting Finder currently ships a synthetic offline sample directory (`lib/services/meeting_finder_service.dart`).
- Research grounding per feature is catalogued in the companion notebook index (Wellbriety/Medicine Wheel -> toolbox pool, PERMA -> gratitude math, MI/sycophancy-mitigation -> coach prompts, SQLCipher -> database pragmas).
"""

def main() -> None:
    parts = [HEADER, "---\n"]
    count = 0
    for rel, tag in TARGETS:
        full = os.path.join(ROOT, rel.replace("/", os.sep))
        if not os.path.exists(full):
            print(f"SKIP (missing): {rel}")
            continue
        with open(full, "r", encoding="utf-8") as f:
            content = f.read().rstrip("\n")
        # Use a 4-backtick fence when the payload itself contains triple backticks
        # (e.g. markdown docs with embedded code blocks) so extraction stays intact.
        fence = "````" if "```" in content else "```"
        parts.append(f"## === START_FILE: {rel} ===\n{fence}{tag}\n{content}\n{fence}\n\n")
        count += 1

    out_path = os.path.join(ROOT, OUT_REL)
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("".join(parts))
    print(f"Wrote {OUT_REL} with {count} files.")

if __name__ == "__main__":
    main()
